Stojanovic/fe 167 change form graphic per comments from ntk
oarepo/oarepo-ui pull request #187
Opened 2024-06-05 08:05 UTC by Ducica

2024-06-06 15:10 UTC, mirekys commented
> It was not possible to use Josh's visually hidden approach, because in our case, we want the layout to be impacted by the hidden element and in his solution, the idea is that the hidden element will not impact the layout, so unfortunately it does not work well for such a use case.

Thats okay if it's not 100% the joshes approach, as the idea was exactly to take up space, just to not be visible

2024-06-07 10:29 UTC, mirekys approved these changes

2024-06-07 10:31 UTC, mirekys requested changes

2024-06-07 10:31 UTC, mirekys commented on oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/ArrayFieldItem/ArrayFieldItem.jsx
> +            id={indexPath}
Element id should be unique across DOM, index number isn't

![Screenshot 2024-06-07 at 12 30 52](https://github.com/oarepo/oarepo-ui/assets/646743/c5479ac0-7a32-4ce8-be47-48d0ee40adf8)

2024-06-07 13:39 UTC, mirekys approved these changes

2024-06-07 14:38 UTC, mirekys requested changes
![Screenshot 2024-06-07 at 16 36 38](https://github.com/oarepo/oarepo-ui/assets/646743/62d3e942-04a0-4118-bff1-271e5119481f)

`id` & `for` attrs seems to now be completely missing from DOM, & there are some unsupported attrs on invenio-group-field div

2024-06-09 08:59 UTC, Ducica commented
@mirekys Sorry about that, now it should be OK. Just for clarity, we already merged this branch to nr-docs, so it will be necessary to merge https://github.com/oarepo/oarepo-ui/pull/187 + https://github.com/Narodni-repozitar/nr-model/pull/37+ https://github.com/oarepo/oarepo-vocabularies/pull/169

2024-06-10 13:10 UTC, Ducica commented
@mirekys Sorry, I fixed it like we discussed. Unfortunately, I had to make a small change to model and vocabularies as well, 
where, for some reason I was sending this formik array to ArrayFieldItem and if you don't destructure it in the arrayFieldItem props, then it just ends up on the dom node. https://github.com/Narodni-repozitar/nr-model/pull/38/files + https://github.com/oarepo/oarepo-vocabularies/pull/170  Thanks!

2024-06-11 07:51 UTC, mirekys approved these changes

2024-06-11 07:51 UTC, merged