added function for extraction of value from multiling array
oarepo/oarepo-ui pull request #221
Opened 2024-08-19 09:51 UTC by Ducica

2024-08-22 08:02 UTC, mirekys requested changes

2024-08-22 08:02 UTC, mirekys commented on oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/util.js
> +  if (multilingualArray.length === 0) {
prease merge into previous if

2024-08-22 08:37 UTC, Ducica commented on oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/util.js
> +  if (multilingualArray.length === 0) {
@mirekys My bad!

2024-08-23 12:50 UTC, mirekys approved these changes

2024-08-23 12:50 UTC, merged